cc_library(name = 'restapi',
    srcs = ['restapi.cc'],
    deps = [
        '//Common/Base:Base',
        '//Common/ThirdParty/jsoncpp-0.5.0/src/lib_json:jsoncpp',
        '//Common/ThirdParty/curl:curl',
        '//Common/Util/HttpClient:curlWrapper',
        '//Common/Util/Encode:encodeUtil',
    ]
)